# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0

"""Current ownership and version-pinned pirlygenes migration inventory guards."""

from pathlib import Path

from oncoref import data_bundle, data_manifest, load_dataset, reference_data

_DATA_DIR = Path(__file__).resolve().parents[1] / "oncoref" / "data"

_BUCKETS = {
    "WHEEL": set(data_manifest.WHEEL),
    "BUNDLE": set(data_manifest.BUNDLE),
    "PLANNED": set(data_manifest.PLANNED),
    "SUPERSEDED": set(data_manifest.SUPERSEDED),
    "OUT_OF_SCOPE": set(data_manifest.OUT_OF_SCOPE),
}


def test_every_pirlygenes_dataset_is_classified():
    # Every asset in the exact historical migration snapshot has one decision.
    classified = set().union(*_BUCKETS.values())
    unclassified = data_manifest.PIRLYGENES_MIGRATION_SNAPSHOT - classified
    assert not unclassified, f"unclassified pirlygenes datasets: {sorted(unclassified)}"


def test_buckets_are_disjoint():
    names = list(_BUCKETS)
    for i, a in enumerate(names):
        for b in names[i + 1 :]:
            overlap = _BUCKETS[a] & _BUCKETS[b]
            assert not overlap, f"{a} & {b} overlap: {sorted(overlap)}"


def test_classification_only_covers_known_pirlygenes_data():
    # A bucket entry that isn't a real pirlygenes asset is a typo/stale classification
    # (HPA + SOURCE are runtime/derived, not pirlygenes files, so excluded). The
    # oncoref-originated bundle members are generated by the rebuilt expression
    # pipeline, not copied from the frozen pirlygenes inventory.
    classified = set().union(*_BUCKETS.values())
    allowed_originated = set(data_manifest.BUNDLE_ORIGINATED) | set(data_manifest.BUNDLE_TRUFFLEPIG)
    stray = classified - data_manifest.PIRLYGENES_MIGRATION_SNAPSHOT - allowed_originated
    assert not stray, f"classified names not in the pirlygenes snapshot: {sorted(stray)}"


def _wheel_file_exists(name: str) -> bool:
    return any((_DATA_DIR / f"{name}{ext}").exists() for ext in (".csv", ".csv.gz", ".yaml"))


def test_wheel_tables_actually_ship():
    missing = [n for n in data_manifest.WHEEL if not _wheel_file_exists(n)]
    assert not missing, f"WHEEL tables not present in the wheel: {missing}"


#: Bundled datasets that ``get_data`` resolves but that no manifest bucket names
#: yet — pre-existing inventory gaps, recorded here instead of hidden. Each one
#: is a real dataset a typed accessor reads, so each still needs a deliberate
#: (name, category, description) entry written for it; they are NOT classified
#: blindly here. A newly added bundled dataset must be registered in the
#: manifest, never appended to this list.
_UNREGISTERED_BUNDLED_DATASETS = frozenset(
    {
        # per-fusion citation audit behind cancer-fusions (oncoref.fusions)
        "cancer-fusion-citation-audit",
        # curated ICI response long table + its wider evidence base and source
        # locator audit (oncoref.ici)
        "cancer-ici-response",
        "cancer-ici-response-estimates",
        "cancer-ici-source-locator-audit",
        # per-gene citation audit behind cancer-key-genes (oncoref.cancer_genes)
        "cancer-key-gene-citation-audit",
        # cancer type -> normal tissue of origin map (oncoref.cancer_types)
        "cancer-normal-tissue-map",
        # per-type TMB source audit behind cancer-tmb (oncoref.tmb)
        "cancer-tmb-source-audit",
        # the canonical Ensembl gene universe (oncoref.gene_ids)
        "canonical-gene-space",
        # per-sample diagnosis mapping for one expression source, referenced by
        # expression_sources.yaml rather than by a typed accessor
        "gse294016-sample-diagnoses",
    }
)


def _bundled_dataset_names() -> set[str]:
    """Names ``get_data`` resolves to a file shipped inside ``oncoref/data``."""
    return {
        name
        for name, path in load_dataset._dataset_paths().items()
        if path.resolve().parent == _DATA_DIR
    }


def _registered_dataset_names() -> set[str]:
    """Every name any manifest bucket accounts for.

    Shared by both allowlist tests: computing "registered" two different ways
    would let a dataset registered in one bucket satisfy the first test while
    still looking unregistered to the second, leaving a stale allowlist entry
    that nothing flags.
    """
    return (
        set(data_manifest.WHEEL)
        | set(data_manifest.CANCERDATA_ORIGINATED)
        | set(data_manifest.BUNDLE)
        | set(data_manifest.SUPERSEDED)
        | set(data_manifest.OUT_OF_SCOPE)
    )


def test_every_bundled_dataset_is_in_the_manifest():
    # The other direction of test_wheel_tables_actually_ship: a dataset that ships
    # in the wheel but is in no manifest bucket is invisible to catalog.inventory()
    # and `oncoref data list`, so shipping one is a manifest bug.
    registered = _registered_dataset_names()
    shipped = _bundled_dataset_names()
    unregistered = shipped - registered - _UNREGISTERED_BUNDLED_DATASETS
    assert not unregistered, f"bundled datasets missing from the manifest: {sorted(unregistered)}"


def test_unregistered_bundled_dataset_allowlist_is_current():
    # Keep the recorded gap honest: every allowlisted name must still ship and
    # still be unregistered, so registering or deleting one forces its removal.
    shipped = _bundled_dataset_names()
    registered = _registered_dataset_names()
    gone = _UNREGISTERED_BUNDLED_DATASETS - shipped
    assert not gone, f"allowlisted datasets no longer shipped — drop them: {sorted(gone)}"
    now_registered = _UNREGISTERED_BUNDLED_DATASETS & registered
    assert not now_registered, (
        f"allowlisted datasets are now in the manifest — drop them: {sorted(now_registered)}"
    )


def test_planned_tables_not_yet_present():
    # PLANNED = still to port; if one is already in data/, move it to WHEEL.
    present = [n for n in data_manifest.PLANNED if _wheel_file_exists(n)]
    assert not present, f"PLANNED tables already shipped — promote to WHEEL: {present}"


def test_bundle_matches_downloadable_paths():
    bundle_stems = {p.removesuffix(".csv") for p in data_bundle.DOWNLOADABLE_PATHS}
    assert bundle_stems == set(data_manifest.BUNDLE)
    assert set(data_manifest.BUNDLE_ORIGINATED).isdisjoint(
        data_manifest.PIRLYGENES_MIGRATION_SNAPSHOT
    )
    assert set(data_manifest.BUNDLE_TRUFFLEPIG).isdisjoint(
        data_manifest.PIRLYGENES_MIGRATION_SNAPSHOT
    )


def test_hpa_matches_reference_sources():
    assert set(data_manifest.HPA) == set(reference_data.REFERENCE_SOURCES)


def test_oncoref_originated_tables_ship():
    # The wheel tables oncoref generates itself (CTA, proteoform groups, the
    # source-matrix registry) must actually be present and appear in the inventory.
    from oncoref import catalog

    missing = [n for n in data_manifest.CANCERDATA_ORIGINATED if not _wheel_file_exists(n)]
    assert not missing, f"oncoref-originated tables not shipped: {missing}"
    inv = {r["name"] for r in catalog.inventory()}
    assert set(data_manifest.CANCERDATA_ORIGINATED) <= inv


def test_originated_not_in_pirlygenes_classification():
    # oncoref-originated tables are NOT pirlygenes files, so must not collide
    # with the pirlygenes-derived buckets.
    classified = (
        set(data_manifest.WHEEL) | set(data_manifest.PLANNED) | set(data_manifest.OUT_OF_SCOPE)
    )
    assert set(data_manifest.CANCERDATA_ORIGINATED).isdisjoint(classified)


def test_pirlygenes_migration_snapshot_has_exact_provenance():
    assert data_manifest.PIRLYGENES_MIGRATION_SNAPSHOT_METADATA == {
        "repository": "pirl-unc/pirlygenes",
        "ref": "v5.22.80",
        "commit": "bb6679e39029218e93acb2e54317a8d4ff98f424",
        "data_path": "pirlygenes/data",
        "captured_at": "2026-06-12",
    }
