# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""oncoref — curated cancer reference data (ontology, TMB, incidence/
mortality, and expression) with a single fetch/cache surface.

Bottom-of-stack: depends only on pandas/numpy/pyarrow, never on the analysis
or target-selection libraries that consume it.
"""

from .apd1 import cancer_apd1_response, cancer_apd1_response_df
from .cancer_types import (
    CANCER_TYPE_ALIASES,
    CANCER_TYPE_NAMES,
    cancer_lineage_group,
    cancer_lineage_group_overrides,
    cancer_lineage_groups,
    cancer_subtype_group,
    cancer_subtype_groupings,
    cancer_type_ancestors,
    cancer_type_descendants,
    cancer_type_families,
    cancer_type_info,
    cancer_type_lineage,
    cancer_type_registry,
    cancer_type_subtypes_of,
    cancer_type_synonyms,
    cancer_type_tree,
    cancer_types_by_tissue,
    cancer_types_in_family,
    canonical_cancer_code,
    cohort_aggregate_members,
    cohort_aggregates,
    cohort_aggregates_df,
    cohort_kind,
    cohort_registry,
    cohort_registry_df,
    family_display_name,
    format_cancer_code_label,
    fusion_status,
    is_mixture_cohort,
    known_cohort_ids,
    mixture_cohort_codes,
    resolve_cancer_type,
    sarcoma_lineage_codes,
    tissue_of_origin,
    viral_status,
)
from .coverage import (
    addressable_fraction,
    addressable_fraction_by_cohort,
    cta_patient_fractions,
    greedy_coverage,
    mean_antigens_per_patient,
    mean_antigens_per_patient_by_cohort,
)
from .cta import (
    cta_candidate_references,
    cta_df,
    cta_evidence,
    cta_excluded_gene_names,
    cta_filtered_gene_ids,
    cta_filtered_gene_names,
    cta_gene_id_to_name,
    cta_gene_ids,
    cta_gene_names,
    cta_never_expressed_gene_names,
    cta_unfiltered_gene_ids,
    cta_unfiltered_gene_names,
)
from .expression import (
    SHARD_DATASETS,
    ShardDataset,
    available_percentile_cohorts,
    available_representative_cohorts,
    available_within_sample_cohorts,
    cohort_gene_percentiles,
    cohort_mean_expression,
    cohort_stats,
    gene_cohort_mean_expression,
    gene_cohort_percentiles,
    gene_cohort_stats,
    gene_per_sample_expression,
    gene_pooled_cohort_stats,
    gene_representative_samples,
    gene_within_sample_top_fraction,
    pan_cancer_expression,
    per_sample_expression,
    pooled_cohort_stats,
    proteoform_cohort_mean_expression,
    proteoform_cohort_percentiles,
    proteoform_cohort_stats,
    proteoform_per_sample_expression,
    proteoform_pooled_cohort_stats,
    proteoform_representative_samples,
    proteoform_within_sample_top_fraction,
    representative_cohort_samples,
    within_sample_top_fraction,
)
from .expression_engine import aggregate_transcripts_to_genes, id_columns, sample_columns
from .expression_registry import (
    ExpressionSource,
    expression_source,
    expression_sources,
    expression_sources_df,
    sources_for_cancer_code,
)
from .fusions import (
    cancer_fusions,
    cancer_fusions_df,
    cancer_types_with_fusion,
    fusion_partners,
    protein_family,
)
from .gene_families import TECHNICAL_RNA_FAMILIES
from .gene_ids import (
    canonical_gene_id,
    canonical_gene_ids,
    ensembl_id_aliases,
    resolve_ensembl_id,
    resolve_symbol,
    unversioned,
)
from .gene_qc import TECHNICAL_RNA_GROUPS, GeneQcClass, classify_gene_qc, is_rescue_feature
from .genome import (
    aggregate_gene_expression,
    canonical_gene_id_and_name,
    canonical_gene_ids_and_names,
    find_gene_id_by_name,
    find_gene_name_from_ensembl_gene_id,
    find_gene_name_from_ensembl_transcript_id,
    genomes,
)
from .hpa import (
    gene_cell_type_ntpm,
    gene_protein_tissues,
    gene_tissue_ntpm,
    hpa_normal_tissue,
    hpa_rna_consensus,
    hpa_single_cell,
)
from .ici import (
    PROPORTION_METRICS,
    REGIMEN_FALLBACK,
    REGIMEN_LABELS,
    cancer_ici_regimen,
    cancer_ici_response,
    cancer_ici_response_df,
    cancer_ici_response_estimates_df,
    ici_regimens,
    pooled_ici_response,
)
from .incidence import (
    burden_category,
    cancer_burden,
    cancer_burden_df,
    cancer_code_burden_map,
)
from .normalization import (
    BIOLOGICAL_FRACTION,
    OTHER_TECHNICAL_FRACTION,
    RIBOSOMAL_PROTEIN_FRACTION,
    TECHNICAL_FRACTION,
    clean_tpm,
    drop_technical_rna,
    filter_technical_rna,
    fpkm_to_tpm,
    is_expression_value_col,
    log1p_transform,
    log2_transform,
    normalize_expression,
    normalize_technical_rna_columns,
    normalize_technical_rna_long_table,
    normalize_to_housekeeping,
    percentile_rank,
    renormalize_to_million,
    tpm_to_housekeeping_normalized,
)
from .peptides import (
    cta_specific_9mer_counts,
    cta_specific_9mer_load,
    cta_specific_9mer_weights,
)
from .proteoforms import (
    collapse_to_proteoforms,
    expression_level,
    gene_to_proteoform,
    gene_to_proteoform_id,
    proteoform_aliases,
    proteoform_for_gene,
    proteoform_group_map,
    proteoform_groups,
    proteoform_key,
    proteoform_members_for_gene,
    proteoform_symbol,
    proteoform_symbol_map,
)
from .response_signatures import (
    response_signature_direction,
    response_signature_genes,
    response_signature_names,
    response_signatures_df,
    signature_score,
)
from .samples import (
    sample_counts_by_cancer_code,
    sample_manifest,
    samples_for_cancer_code,
    samples_for_cohort,
)
from .tmb import cancer_tmb, cancer_tmb_df
from .version import __version__

__all__ = [
    # expression sources + per-sample curation
    "BIOLOGICAL_FRACTION",
    # ontology / registry
    "CANCER_TYPE_ALIASES",
    "CANCER_TYPE_NAMES",
    "OTHER_TECHNICAL_FRACTION",
    "PROPORTION_METRICS",
    "REGIMEN_FALLBACK",
    "REGIMEN_LABELS",
    "RIBOSOMAL_PROTEIN_FRACTION",
    "SHARD_DATASETS",
    "TECHNICAL_FRACTION",
    "TECHNICAL_RNA_FAMILIES",
    "TECHNICAL_RNA_GROUPS",
    "ExpressionSource",
    "GeneQcClass",
    "ShardDataset",
    "__version__",
    # expression (read accessors over the downloadable bundle)
    "addressable_fraction",
    "addressable_fraction_by_cohort",
    "aggregate_gene_expression",
    "aggregate_transcripts_to_genes",
    "available_percentile_cohorts",
    "available_representative_cohorts",
    "available_within_sample_cohorts",
    "burden_category",
    # anti-PD-1 response
    "cancer_apd1_response",
    "cancer_apd1_response_df",
    # incidence / mortality
    "cancer_burden",
    "cancer_burden_df",
    "cancer_code_burden_map",
    "cancer_fusions",
    "cancer_fusions_df",
    "cancer_ici_regimen",
    "cancer_ici_response",
    "cancer_ici_response_df",
    "cancer_ici_response_estimates_df",
    "cancer_lineage_group",
    "cancer_lineage_group_overrides",
    "cancer_lineage_groups",
    "cancer_subtype_group",
    "cancer_subtype_groupings",
    # TMB
    "cancer_tmb",
    "cancer_tmb_df",
    "cancer_type_ancestors",
    "cancer_type_descendants",
    "cancer_type_families",
    "cancer_type_info",
    "cancer_type_lineage",
    "cancer_type_registry",
    "cancer_type_subtypes_of",
    "cancer_type_synonyms",
    "cancer_type_tree",
    "cancer_types_by_tissue",
    "cancer_types_in_family",
    "cancer_types_with_fusion",
    "canonical_cancer_code",
    "canonical_gene_id",
    "canonical_gene_id_and_name",
    "canonical_gene_ids",
    "canonical_gene_ids_and_names",
    "classify_gene_qc",
    "clean_tpm",
    "cohort_aggregate_members",
    # cohort vocabulary
    "cohort_aggregates",
    "cohort_aggregates_df",
    "cohort_gene_percentiles",
    "cohort_kind",
    "cohort_mean_expression",
    "cohort_registry",
    "cohort_registry_df",
    "cohort_stats",
    "collapse_to_proteoforms",
    "cta_candidate_references",
    "cta_df",
    # cancer-testis antigens
    "cta_evidence",
    "cta_excluded_gene_names",
    "cta_filtered_gene_ids",
    "cta_filtered_gene_names",
    "cta_gene_id_to_name",
    "cta_gene_ids",
    "cta_gene_names",
    "cta_never_expressed_gene_names",
    "cta_patient_fractions",
    "cta_specific_9mer_counts",
    "cta_specific_9mer_load",
    "cta_specific_9mer_weights",
    "cta_unfiltered_gene_ids",
    "cta_unfiltered_gene_names",
    "drop_technical_rna",
    "ensembl_id_aliases",
    "expression_level",
    "expression_source",
    "expression_sources",
    "expression_sources_df",
    "family_display_name",
    "filter_technical_rna",
    "find_gene_id_by_name",
    "find_gene_name_from_ensembl_gene_id",
    "find_gene_name_from_ensembl_transcript_id",
    "format_cancer_code_label",
    "fpkm_to_tpm",
    "fusion_partners",
    "fusion_status",
    "gene_cell_type_ntpm",
    "gene_cohort_mean_expression",
    "gene_cohort_percentiles",
    "gene_cohort_stats",
    "gene_per_sample_expression",
    "gene_pooled_cohort_stats",
    "gene_protein_tissues",
    "gene_representative_samples",
    "gene_tissue_ntpm",
    "gene_to_proteoform",
    "gene_to_proteoform_id",
    "gene_within_sample_top_fraction",
    "genomes",
    "greedy_coverage",
    "hpa_normal_tissue",
    # HPA normal-tissue reference data
    "hpa_rna_consensus",
    "hpa_single_cell",
    "ici_regimens",
    "id_columns",
    "is_expression_value_col",
    "is_mixture_cohort",
    "is_rescue_feature",
    "known_cohort_ids",
    "log1p_transform",
    "log2_transform",
    "mean_antigens_per_patient",
    "mean_antigens_per_patient_by_cohort",
    "mixture_cohort_codes",
    "normalize_expression",
    "normalize_technical_rna_columns",
    "normalize_technical_rna_long_table",
    "normalize_to_housekeeping",
    "pan_cancer_expression",
    "per_sample_expression",
    "percentile_rank",
    "pooled_cohort_stats",
    "pooled_ici_response",
    "protein_family",
    "proteoform_aliases",
    "proteoform_cohort_mean_expression",
    "proteoform_cohort_percentiles",
    "proteoform_cohort_stats",
    "proteoform_for_gene",
    "proteoform_group_map",
    "proteoform_groups",
    "proteoform_key",
    "proteoform_members_for_gene",
    "proteoform_per_sample_expression",
    "proteoform_pooled_cohort_stats",
    "proteoform_representative_samples",
    "proteoform_symbol",
    "proteoform_symbol_map",
    "proteoform_within_sample_top_fraction",
    "renormalize_to_million",
    "representative_cohort_samples",
    "resolve_cancer_type",
    "resolve_ensembl_id",
    "resolve_symbol",
    "response_signature_direction",
    "response_signature_genes",
    "response_signature_names",
    "response_signatures_df",
    "sample_columns",
    "sample_counts_by_cancer_code",
    "sample_manifest",
    "samples_for_cancer_code",
    "samples_for_cohort",
    "sarcoma_lineage_codes",
    "signature_score",
    "sources_for_cancer_code",
    "tissue_of_origin",
    "tpm_to_housekeeping_normalized",
    "unversioned",
    "viral_status",
    "within_sample_top_fraction",
]
