# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Pure build-time transforms that produce the precomputed expression artifacts.

This is the **build-time** half of the expression layer — the public counterpart
to the read-time accessors in :mod:`oncoref.expression`. Each shipped shard
dataset is generated by one core here:

* :func:`cohort_percentile_vectors` → the ``cancer-reference-expression-percentiles``
  shards (per-gene cohort breakpoints, :data:`PERCENTILE_BREAKPOINTS`);
* :func:`cohort_medoids` → the ``cancer-reference-expression-representatives`` shards
  (representative sample picks spanning within-cohort variation);
* :func:`within_sample_top_fractions` → the within-sample-top shards
  (:data:`WITHIN_SAMPLE_THRESHOLDS`);
* :func:`sum_proteoform_tpm` → the proteoform-summed artifacts.

Each shard's :class:`~oncoref.expression.ShardDataset` names its core via
``build_attr``, so :mod:`oncoref.expression` can regenerate a missing cohort
on demand by calling back into this module.

Kept deliberately dependency-light (pandas/numpy only) and free of I/O, so the
cores are unit-testable without any data bundle (see ``tests/test_build_generators``)
and the ``scripts/generate_*`` / ``scripts/rebuild_expression_artifacts`` wrappers
stay thin. Renamed from the former private ``_build`` module so it can be
referenced and documented as the public build-time API.
"""

from __future__ import annotations

import re
import shutil
import urllib.request
from collections.abc import Iterable, Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Literal

import numpy as np
import pandas as pd
import yaml

from .expression_engine import (
    canonicalize_source_gene_matrix,
    coerce_source_expression_values,
    id_columns,
    sample_columns,
)

SourceExpressionUnit = Literal["TPM", "FPKM", "RPKM", "log2(TPM+1)", "raw_counts"]
GEO_MATRIX_SOURCE_TYPE = "geo-matrix"

_SOURCE_SYMBOL_COLUMN_CANDIDATES = (
    "Symbol",
    "symbol",
    "gene_symbol",
    "gene_name",
    "external_gene_name",
)

#: Per-gene cohort percentile breakpoints — dense in the actionable upper tail so
#: a consumer can place a sample's gene as a percentile rank within the cohort
#: (matches the shipped ``cancer-reference-expression-percentiles`` schema: 26
#: ``p{n}`` columns from p0 to p100). Read back by ``expression.cohort_gene_percentiles``.
PERCENTILE_BREAKPOINTS = (
    0,
    1,
    5,
    10,
    15,
    20,
    25,
    30,
    35,
    40,
    45,
    50,
    55,
    60,
    65,
    70,
    75,
    80,
    85,
    90,
    95,
    96,
    97,
    98,
    99,
    100,
)

#: threshold (within-sample percentile rank) -> output column name.
#: 0.95 = "in the top 5% of expressed genes in that sample".
WITHIN_SAMPLE_THRESHOLDS = {
    0.99: "frac_samples_top1pct",
    0.95: "frac_samples_top5pct",
    0.90: "frac_samples_top10pct",
}


@dataclass(frozen=True)
class GeoMatrixSource:
    """One generic supplementary expression matrix source.

    The source file is a row-by-gene matrix with one column per sample plus a
    gene identifier column (or, with ``transposed=True``, a sample-by-row matrix
    that is transposed before processing). This is the oncoref-owned replacement
    for the generic pirlygenes GEO/GSA/cBioPortal matrix builder: it handles
    source download, raw parse diagnostics, unit-to-TPM conversion, canonical gene
    mapping, per-code routing, per-sample QC, and oncoref-style per-sample parquet
    output. Source-specific wrappers should supply the routing/filter functions;
    the identity/QC contract remains here.
    """

    cancer_code: str | list[str]
    source_cohort: str
    file_name: str
    unit: SourceExpressionUnit
    file_url: str | None = None
    source_project: str | None = None
    citation: str | None = None
    gene_id_col: str = ""
    symbol_col: str | None = None
    drop_cols: tuple[str, ...] = ()
    sep: str = "\t"
    transposed: bool = False
    sample_filter: Callable[[list[str]], list[str]] | None = None
    sample_to_cancer_code: Callable[[str], str | None] | None = None
    source_scale_class: str | None = None
    linear_tpm_comparable: bool | None = None
    tpm_proxy: bool | None = None


@dataclass(frozen=True)
class SourceMatrixBuildResult:
    """Artifacts produced by :func:`build_source_matrices`."""

    source: GeoMatrixSource
    matrices: dict[str, pd.DataFrame]
    matrix_paths: dict[str, Path]
    mapping_audit: pd.DataFrame
    parse_diagnostics: pd.DataFrame
    sample_qc: pd.DataFrame
    sidecar_paths: dict[str, Path]


def _source_entries_from_registry(registry_path: str | Path | None = None) -> list[dict]:
    if registry_path is None:
        from .expression_registry import expression_source_registry_entries

        return [dict(entry) for entry in expression_source_registry_entries()]
    else:
        with Path(registry_path).open() as handle:
            payload = yaml.safe_load(handle) or {}
    entries = payload.get("sources", [])
    if not isinstance(entries, list):
        raise ValueError("expression source registry must contain a list-valued 'sources' key")
    return [dict(entry) for entry in entries]


def geo_matrix_source_entries(registry_path: str | Path | None = None) -> list[dict]:
    """Raw ``source_type: geo-matrix`` entries from ``expression_sources.yaml``.

    This is the registry/config half of the source-matrix builder contract. The
    returned dictionaries preserve the source YAML fields so build scripts can
    inspect provenance or source-specific notes, while
    :func:`geo_matrix_source_from_entry` converts one entry into the executable
    :class:`GeoMatrixSource` object used by :func:`build_source_matrices`.
    """
    return [
        entry
        for entry in _source_entries_from_registry(registry_path)
        if entry.get("source_type") == GEO_MATRIX_SOURCE_TYPE
    ]


def _compile_sample_filter(spec: Mapping | None) -> Callable[[list[str]], list[str]] | None:
    if not spec:
        return None
    include = str(spec["include_match"]) if "include_match" in spec else None
    exclude = str(spec["exclude_match"]) if "exclude_match" in spec else None
    include_re = re.compile(include) if include else None
    exclude_re = re.compile(exclude) if exclude else None

    def _filter(samples: list[str]) -> list[str]:
        out = []
        for sample in samples:
            if include_re is not None and not include_re.search(str(sample)):
                continue
            if exclude_re is not None and exclude_re.search(str(sample)):
                continue
            out.append(str(sample))
        return out

    return _filter


def _compile_sample_to_cancer_code(
    spec: Mapping | None,
) -> Callable[[str], str | None] | None:
    rules = (spec or {}).get("rules", [])
    if not rules:
        return None
    compiled = [(re.compile(str(rule["match"])), str(rule["cancer_code"])) for rule in rules]

    def _dispatch(sample_id: str) -> str | None:
        for regex, code in compiled:
            if regex.search(str(sample_id)):
                return code
        return None

    return _dispatch


def _coerce_source_expression_unit(unit: str) -> SourceExpressionUnit:
    normalized = str(unit).strip()
    aliases = {
        "tpm": "TPM",
        "fpkm": "FPKM",
        "rpkm": "RPKM",
        "raw_counts": "raw_counts",
        "raw counts": "raw_counts",
        "log2-tpm": "log2(TPM+1)",
        "log2_tpm": "log2(TPM+1)",
        "log2(tpm+1)": "log2(TPM+1)",
        "log2(tpm + 1)": "log2(TPM+1)",
    }
    coerced = aliases.get(normalized.lower(), normalized)
    if coerced not in {"TPM", "FPKM", "RPKM", "log2(TPM+1)", "raw_counts"}:
        raise ValueError(f"unsupported geo-matrix source unit: {unit!r}")
    return coerced  # type: ignore[return-value]


def geo_matrix_source_from_entry(entry: Mapping) -> GeoMatrixSource:
    """Convert one registry YAML entry into an executable :class:`GeoMatrixSource`."""
    if entry.get("source_type") != GEO_MATRIX_SOURCE_TYPE:
        raise ValueError(
            f"source {entry.get('id')!r} has source_type={entry.get('source_type')!r}, "
            f"not {GEO_MATRIX_SOURCE_TYPE!r}"
        )
    cancer_codes = [str(code) for code in entry.get("cancer_codes", [])]
    if not cancer_codes:
        raise ValueError(f"source {entry.get('id')!r} has no cancer_codes")
    cancer_code: str | list[str] = cancer_codes[0] if len(cancer_codes) == 1 else cancer_codes
    return GeoMatrixSource(
        cancer_code=cancer_code,
        source_cohort=str(entry["source_cohort"]),
        source_project=entry.get("source_project"),
        citation=entry.get("citation"),
        file_url=entry.get("file_url"),
        file_name=str(entry["file_name"]),
        unit=_coerce_source_expression_unit(str(entry["unit"])),
        gene_id_col=str(entry.get("gene_id_col", "")),
        symbol_col=entry.get("symbol_col"),
        drop_cols=tuple(str(col) for col in entry.get("drop_cols", [])),
        sep=str(entry.get("sep", "\t")),
        transposed=bool(entry.get("transposed", False)),
        sample_filter=_compile_sample_filter(entry.get("sample_filter")),
        sample_to_cancer_code=_compile_sample_to_cancer_code(entry.get("sample_to_cancer_code")),
        source_scale_class=entry.get("source_scale_class"),
        linear_tpm_comparable=entry.get("linear_tpm_comparable"),
        tpm_proxy=entry.get("tpm_proxy"),
    )


def geo_matrix_source_from_registry(
    source_id: str,
    registry_path: str | Path | None = None,
) -> GeoMatrixSource:
    """Load one ``source_type: geo-matrix`` entry from ``expression_sources.yaml``."""
    for entry in _source_entries_from_registry(registry_path):
        if entry.get("id") == source_id:
            return geo_matrix_source_from_entry(entry)
    raise KeyError(f"source id {source_id!r} not found in expression source registry")


def _csv_engine(sep: str) -> str:
    return "python" if len(sep) > 1 or "\\" in sep else "c"


def _rename_unnamed_row_id(df: pd.DataFrame, row_id_col: str) -> tuple[pd.DataFrame, str]:
    if str(row_id_col).startswith("Unnamed"):
        df = df.rename(columns={row_id_col: "source_row_id"})
        row_id_col = "source_row_id"
    return df, row_id_col


def _detect_symbol_col(df: pd.DataFrame, row_id_col: str, symbol_col: str | None) -> str | None:
    if symbol_col is not None:
        if symbol_col not in df.columns:
            raise ValueError(f"source symbol column {symbol_col!r} is not in expression data")
        return symbol_col
    by_lower = {str(col).lower(): col for col in df.columns}
    for candidate in _SOURCE_SYMBOL_COLUMN_CANDIDATES:
        col = by_lower.get(candidate.lower())
        if col is not None and col != row_id_col:
            return str(col)
    return None


def source_expression_value_columns(
    df: pd.DataFrame,
    *,
    row_id_col: str | None = None,
    symbol_col: str | None = None,
    value_cols: Iterable[str] | None = None,
) -> list[str]:
    """Sample/value columns in a raw source expression matrix.

    Explicit ``value_cols`` are validated. Otherwise this excludes the source row
    identifier and optional symbol column. This is intentionally source-matrix
    scoped, distinct from :func:`oncoref.expression_engine.sample_columns`, whose
    identity columns apply after canonicalization.
    """
    if value_cols is not None:
        cols = [str(c) for c in value_cols]
        missing = [c for c in cols if c not in df.columns]
        if missing:
            raise ValueError(f"requested source expression value columns are missing: {missing}")
        return cols
    excluded = {c for c in (row_id_col, symbol_col) if c is not None}
    return [str(c) for c in df.columns if c not in excluded]


def read_source_expression_matrix(
    path: str | Path,
    *,
    sep: str = "\t",
    gene_id_col: str = "",
    symbol_col: str | None = None,
    drop_cols: Iterable[str] = (),
    transposed: bool = False,
) -> pd.DataFrame:
    """Read a source expression matrix while preserving raw value strings.

    Non-sample annotation columns that are neither the row-id column nor a known
    symbol column are dropped when they contain no parseable numeric values. Value
    coercion is deliberately deferred to
    :func:`oncoref.expression_engine.coerce_source_expression_values` so parse
    diagnostics can distinguish missing, non-parsing, literal-zero, and measured
    numeric cells.

    The returned frame stores ``row_id_col`` and ``symbol_col`` in ``DataFrame``
    attrs for downstream builder helpers.
    """
    read_kwargs = {"sep": sep, "engine": _csv_engine(sep), "dtype": str}
    df = pd.read_csv(Path(path), **read_kwargs)
    if df.empty:
        raise ValueError(f"source expression matrix is empty: {path}")

    if transposed:
        source_sample_col = gene_id_col or str(df.columns[0])
        if source_sample_col not in df.columns:
            raise ValueError(f"sample ID column {source_sample_col!r} is not in expression data")
        df = df.dropna(subset=[source_sample_col]).set_index(source_sample_col).T.reset_index()
        row_id_col = "source_row_id"
        df = df.rename(columns={"index": row_id_col})
        symbol_col = None
    else:
        row_id_col = gene_id_col or str(df.columns[0])
        if row_id_col not in df.columns:
            raise ValueError(f"gene_id_col={row_id_col!r} is not in columns: {list(df.columns)}")
        df, row_id_col = _rename_unnamed_row_id(df, row_id_col)
        symbol_col = _detect_symbol_col(df, row_id_col, symbol_col)

    df[row_id_col] = df[row_id_col].astype(str).str.strip()
    df = df[df[row_id_col] != ""].reset_index(drop=True)
    for col in drop_cols:
        if col in df.columns and col not in {row_id_col, symbol_col}:
            df = df.drop(columns=col)
    for col in list(df.columns):
        if col in {row_id_col, symbol_col}:
            continue
        numeric = pd.to_numeric(df[col], errors="coerce")
        if numeric.notna().sum() == 0:
            df = df.drop(columns=col)

    df.attrs["row_id_col"] = row_id_col
    df.attrs["symbol_col"] = symbol_col
    return df


def _per_sample_to_tpm(values: pd.DataFrame) -> pd.DataFrame:
    sums = values.sum(axis=0)
    return values.div(sums.where(sums > 0), axis=1).fillna(0.0) * 1_000_000.0


def _inverse_log2_tpm(values: pd.DataFrame) -> pd.DataFrame:
    arr = np.power(2.0, values.to_numpy(dtype=float)) - 1.0
    arr[arr < 0] = 0.0
    return pd.DataFrame(arr, index=values.index, columns=values.columns)


def normalize_source_matrix_to_tpm(
    df: pd.DataFrame,
    *,
    unit: SourceExpressionUnit,
    row_id_col: str | None = None,
    symbol_col: str | None = None,
    value_cols: Iterable[str] | None = None,
    gene_lengths_kb: pd.Series | Mapping[str, float] | None = None,
) -> pd.DataFrame:
    """Convert a raw source matrix to linear per-sample TPM values.

    ``TPM``, ``FPKM``, and ``RPKM`` inputs are renormalized per sample to sum to
    one million because many published matrices are filtered before release.
    ``log2(TPM+1)`` is inverse-transformed but not renormalized, matching the
    Treehouse-style input contract. ``raw_counts`` requires ``gene_lengths_kb``
    indexed by source row ID and performs length normalization before the TPM
    renormalization.
    """
    row_id_col = row_id_col or df.attrs.get("row_id_col") or str(df.columns[0])
    symbol_col = symbol_col if symbol_col is not None else df.attrs.get("symbol_col")
    cols = source_expression_value_columns(
        df, row_id_col=row_id_col, symbol_col=symbol_col, value_cols=value_cols
    )
    numeric = df[cols].apply(pd.to_numeric, errors="coerce").fillna(0.0).clip(lower=0.0)

    if unit in {"TPM", "FPKM", "RPKM"}:
        values = _per_sample_to_tpm(numeric)
    elif unit == "log2(TPM+1)":
        values = _inverse_log2_tpm(numeric)
    elif unit == "raw_counts":
        if gene_lengths_kb is None:
            raise ValueError("unit='raw_counts' requires gene_lengths_kb")
        lengths = pd.Series(gene_lengths_kb, dtype=float)
        row_ids = df[row_id_col].astype(str).str.split(".", n=1).str[0]
        aligned = row_ids.map(lengths).replace(0, np.nan)
        if aligned.notna().sum() == 0:
            raise ValueError("gene_lengths_kb does not match any source row IDs")
        rpk = numeric.div(aligned.to_numpy(), axis=0).fillna(0.0)
        values = _per_sample_to_tpm(rpk)
    else:  # pragma: no cover - typing should prevent this; keep runtime guard.
        raise ValueError(f"unsupported source expression unit: {unit!r}")

    out_cols = [row_id_col]
    if symbol_col is not None and symbol_col in df.columns:
        out_cols.append(symbol_col)
    out = df[out_cols].copy()
    for col in cols:
        out[col] = values[col].to_numpy(dtype=float)
    out.attrs["row_id_col"] = row_id_col
    out.attrs["symbol_col"] = symbol_col
    out.attrs["source_expression_unit"] = unit
    return out


def source_metadata(
    *,
    source_cohort: str | None = None,
    source_type: str | None = None,
    unit: SourceExpressionUnit | str | None = None,
    source_scale_class: str | None = None,
    linear_tpm_comparable: bool | None = None,
    tpm_proxy: bool | None = None,
) -> dict[str, str | bool | None]:
    """Metadata shape consumed by :func:`expression.sample_expression_qc_from_matrix`."""
    if source_scale_class is None:
        source_scale_class = (
            "linear_rnaseq_tpm"
            if unit in {"TPM", "FPKM", "RPKM", "raw_counts", "log2(TPM+1)"}
            else "unknown"
        )
    if linear_tpm_comparable is None:
        linear_tpm_comparable = source_scale_class == "linear_rnaseq_tpm"
    if tpm_proxy is None:
        tpm_proxy = not bool(linear_tpm_comparable)
    return {
        "source_cohort": source_cohort,
        "source_type": source_type,
        "unit": unit,
        "source_scale_class": source_scale_class,
        "linear_tpm_comparable": bool(linear_tpm_comparable),
        "tpm_proxy": bool(tpm_proxy),
    }


def _download(url: str, dest: Path, *, force: bool = False) -> Path:
    if dest.exists() and dest.stat().st_size > 0 and not force:
        return dest
    dest.parent.mkdir(parents=True, exist_ok=True)
    tmp = dest.with_suffix(dest.suffix + ".part")
    with urllib.request.urlopen(url) as resp, tmp.open("wb") as handle:
        shutil.copyfileobj(resp, handle, length=1024 * 1024)
    tmp.replace(dest)
    return dest


def _artifact_stem(value: str) -> str:
    return "".join(c if c.isalnum() or c in "._-" else "_" for c in value)


def split_source_matrix_by_code(
    matrix: pd.DataFrame,
    cancer_code: str | list[str],
    *,
    sample_to_cancer_code: Callable[[str], str | None] | None = None,
) -> dict[str, list[str]]:
    """Route canonicalized sample columns to cancer codes."""
    samples = sample_columns(matrix)
    if sample_to_cancer_code is None:
        if isinstance(cancer_code, list):
            raise ValueError("cancer_code is a list but no sample_to_cancer_code was provided")
        return {str(cancer_code): samples}

    out: dict[str, list[str]] = {}
    for sample in samples:
        code = sample_to_cancer_code(str(sample))
        if code is not None:
            out.setdefault(str(code), []).append(sample)
    return out


def build_source_matrices(
    source: GeoMatrixSource,
    *,
    cache_dir: str | Path,
    output_dir: str | Path | None = None,
    source_path: str | Path | None = None,
    force_download: bool = False,
    gene_lengths_kb: pd.Series | Mapping[str, float] | None = None,
    high_expression_threshold: float = 1.0,
) -> SourceMatrixBuildResult:
    """Build oncoref source-matrix artifacts for one generic expression source.

    Output matrices are written as ``<CODE>_per_sample_tpm.parquet`` under
    ``output_dir`` (default ``cache_dir / "derived"``), matching the layout that
    :mod:`scripts.stage_source_matrices` consumes before release upload. Sidecars
    include source-row mapping audit, source-value parse diagnostics, and per-sample
    QC manifests. Samples are not dropped here; read/build-time consumers choose
    ``all``/``pass``/``pass_or_warn`` filtering from the QC manifest.
    """
    cache = Path(cache_dir)
    out_dir = Path(output_dir) if output_dir is not None else cache / "derived"
    out_dir.mkdir(parents=True, exist_ok=True)

    file_path = Path(source_path) if source_path is not None else cache / source.file_name
    if not file_path.exists() or force_download:
        if not source.file_url:
            raise ValueError("source_path is absent and GeoMatrixSource.file_url is not set")
        file_path = _download(source.file_url, file_path, force=force_download)

    raw = read_source_expression_matrix(
        file_path,
        sep=source.sep,
        gene_id_col=source.gene_id_col,
        symbol_col=source.symbol_col,
        drop_cols=source.drop_cols,
        transposed=source.transposed,
    )
    row_id_col = raw.attrs["row_id_col"]
    symbol_col = raw.attrs.get("symbol_col")
    raw_value_cols = source_expression_value_columns(
        raw, row_id_col=row_id_col, symbol_col=symbol_col
    )
    if source.sample_filter is not None:
        keep = source.sample_filter(raw_value_cols)
        missing = [c for c in keep if c not in raw.columns]
        if missing:
            raise ValueError(f"sample_filter returned missing sample columns: {missing}")
        raw = raw[[c for c in (row_id_col, symbol_col) if c is not None] + keep].copy()
        raw.attrs["row_id_col"] = row_id_col
        raw.attrs["symbol_col"] = symbol_col
        raw_value_cols = keep
    if not raw_value_cols:
        raise ValueError("source matrix has no sample/value columns")

    _, parse_diagnostics = coerce_source_expression_values(
        raw, value_cols=raw_value_cols, row_id_col=row_id_col, symbol_col=symbol_col
    )
    tpm = normalize_source_matrix_to_tpm(
        raw,
        unit=source.unit,
        row_id_col=row_id_col,
        symbol_col=symbol_col,
        value_cols=raw_value_cols,
        gene_lengths_kb=gene_lengths_kb,
    )
    matrix, audit = canonicalize_source_gene_matrix(
        tpm,
        row_id_col=row_id_col,
        symbol_col=symbol_col,
        value_cols=raw_value_cols,
        high_expression_threshold=high_expression_threshold,
    )
    matrix.attrs["source_value_parse_diagnostics"] = parse_diagnostics

    stem = _artifact_stem(source.source_cohort)
    sidecar_paths: dict[str, Path] = {}
    audit_path = out_dir / f"{stem}_mapping_audit.csv"
    parse_path = out_dir / f"{stem}_parse_diagnostics.csv"
    audit.to_csv(audit_path, index=False)
    parse_diagnostics.to_csv(parse_path, index=False)
    sidecar_paths["mapping_audit"] = audit_path
    sidecar_paths["parse_diagnostics"] = parse_path

    meta = source_metadata(
        source_cohort=source.source_cohort,
        source_type=source.source_project,
        unit=source.unit,
        source_scale_class=source.source_scale_class,
        linear_tpm_comparable=source.linear_tpm_comparable,
        tpm_proxy=source.tpm_proxy,
    )

    from .expression import sample_expression_qc_from_matrix

    matrices: dict[str, pd.DataFrame] = {}
    matrix_paths: dict[str, Path] = {}
    qc_frames: list[pd.DataFrame] = []
    for code, cols in split_source_matrix_by_code(
        matrix,
        source.cancer_code,
        sample_to_cancer_code=source.sample_to_cancer_code,
    ).items():
        if not cols:
            continue
        sub = matrix[[*id_columns(matrix), *cols]].copy()
        sub.attrs = {}
        path = out_dir / f"{_artifact_stem(code)}_per_sample_tpm.parquet"
        sub.to_parquet(path, index=False)
        qc = sample_expression_qc_from_matrix(sub, cancer_type=code, source_metadata=meta)
        qc_path = out_dir / f"{_artifact_stem(code)}_sample_qc.csv"
        qc.to_csv(qc_path, index=False)
        matrices[code] = sub
        matrix_paths[code] = path
        sidecar_paths[f"{code}_sample_qc"] = qc_path
        qc_frames.append(qc)

    if not matrices:
        raise ValueError("no samples were routed to a cancer code")
    sample_qc = pd.concat(qc_frames, ignore_index=True) if qc_frames else pd.DataFrame()
    return SourceMatrixBuildResult(
        source=source,
        matrices=matrices,
        matrix_paths=matrix_paths,
        mapping_audit=audit,
        parse_diagnostics=parse_diagnostics,
        sample_qc=sample_qc,
        sidecar_paths=sidecar_paths,
    )


def sum_proteoform_tpm(
    df: pd.DataFrame,
    group_map: Mapping[str, Iterable[str]],
    sample_cols: Iterable[str] | None = None,
    *,
    group_symbols: Mapping[str, str] | None = None,
) -> pd.DataFrame:
    """Collapse genes that encode an identical protein into one summed row.

    For each proteoform group in ``group_map`` (``{label: member gene IDs}``), the
    per-sample TPM of the member genes is *summed* into a single row labelled by
    the group — the biologically correct unit when reads multi-map between
    identical-protein loci (CTAG1A/CTAG1B, SSX4/SSX4B, the CT47A family, …). Genes
    in no group pass through unchanged.

    This is the pure core behind the runtime ``proteoform_representative_samples``
    accessor; the offline percentile/within-sample generators can apply it first
    so a proteoform-summed artifact and a per-gene one share the same arithmetic.

    ``df`` has ``Ensembl_Gene_ID``, ``Symbol`` and one column per sample. Gene IDs
    are matched version-insensitively. The collapse **reduces the key count** (members
    merge into one row), and the output carries the proteoform identity **without
    overloading the Ensembl ID column** (so it stays a real, joinable ENSG):

      - ``Ensembl_Gene_ID`` — the group's **canonical member** ENSG (the
        lexicographically-smallest member id) for a collapsed group; the gene's own
        ENSG for a singleton. Always a genuine Ensembl id.
      - ``Symbol`` — the single **proteoform symbol** that survives: for a group, the
        value supplied in ``group_symbols`` (the curated alias ``NY-ESO-1`` or the
        prefix-contracted members ``XAGE1A/B``), falling back to the raw members label
        if no ``group_symbols`` entry; the gene's own symbol for a singleton.
      - ``proteoform_members`` — provenance: the group's sorted slash-joined member
        symbols (``CTAG1A/CTAG1B``); the gene's own symbol for a singleton.

    ``group_symbols`` maps a group's members label → its surviving proteoform symbol
    (see :func:`oncoref.proteoforms.proteoform_symbol`). First-appearance row order
    is preserved.

    Summation uses ``min_count=1`` so a missing measurement stays missing: a cell
    that is all-NaN (e.g. a gene absent from a cohort after an outer-merge across
    cohorts) remains NaN rather than collapsing to 0.0 — "not measured" must not
    silently become "measured zero". Within a group, a present member still sums
    even when a sibling is NaN.

    Note: matching is best-effort by gene ID. If the frame's IDs are on a
    different Ensembl basis than the registry, unmatched members simply pass
    through ungrouped (no error) — the build-script anchor check guards the
    registry side; align the bases if a known group fails to collapse.
    """
    cols = list(sample_cols) if sample_cols is not None else sample_columns(df)
    work = df.copy()
    unversioned = work["Ensembl_Gene_ID"].astype(str).str.split(".").str[0]
    gene_to_label: dict[str, str] = {}
    gene_to_canonical: dict[str, str] = {}
    for raw_label, members in group_map.items():
        member_ids = [str(g).split(".")[0] for g in members]
        canonical = min(member_ids)  # stable, collision-free representative ENSG
        for mid in member_ids:
            gene_to_label[mid] = str(raw_label)
            gene_to_canonical[mid] = canonical

    label = unversioned.map(gene_to_label)
    in_group = label.notna()
    canonical = unversioned.map(gene_to_canonical)

    work["_key"] = label.where(in_group, unversioned)
    # ENSG stays a real Ensembl id (canonical member / own id), never the label.
    work["_out_id"] = canonical.where(in_group, work["Ensembl_Gene_ID"].astype(str))
    # Symbol = the single surviving proteoform symbol (alias / contracted members) for
    # a group, the gene's own symbol for a singleton.
    group_sym = label.map(group_symbols) if group_symbols else label
    work["_out_symbol"] = group_sym.where(in_group, work["Symbol"].astype(str))
    # proteoform_members = the sorted slash-joined members (provenance) / own symbol.
    work["_out_members"] = label.where(in_group, work["Symbol"].astype(str))
    # proteoform_key = THE reduced identity: the gene's own ENSG when it uniquely
    # owns its protein (1:1, singleton), the proteoform symbol when ENSGs were summed
    # away (group). The member ENSGs never appear here.
    work["_out_key"] = work["_out_symbol"].where(in_group, work["_out_id"])

    grouped = work.groupby("_key", sort=False)
    ids = grouped[["_out_key", "_out_id", "_out_symbol", "_out_members"]].first()
    sums = grouped[cols].sum(min_count=1)
    agg = ids.join(sums).rename(
        columns={
            "_out_key": "proteoform_key",
            "_out_id": "Ensembl_Gene_ID",
            "_out_symbol": "Symbol",
            "_out_members": "proteoform_members",
        }
    )
    return agg.reset_index(drop=True)[
        ["proteoform_key", "Ensembl_Gene_ID", "Symbol", "proteoform_members", *cols]
    ]


def within_sample_top_fractions(
    df: pd.DataFrame,
    sample_cols: Iterable[str] | None = None,
    *,
    thresholds: Iterable[float] = tuple(WITHIN_SAMPLE_THRESHOLDS),
) -> pd.DataFrame:
    """Per-gene fraction of a cohort's samples in which the gene is highly
    expressed *within that sample* (signal a).

    For each sample (column), genes are ranked across the whole gene axis into a
    within-sample percentile (``rank(pct=True)``). A gene clears threshold ``t``
    in a sample when its within-sample percentile ≥ ``t``. The per-gene output is
    the fraction of the cohort's samples where it clears ``t`` — i.e. "in what
    fraction of these tumors is this gene among the top ``(1-t)`` of expressed
    genes."

    Returns one row per gene with ``Ensembl_Gene_ID``, ``Symbol``,
    ``frac_samples_top{1,5,10}pct`` (per threshold), and ``n_samples``.
    """
    cols = list(sample_cols) if sample_cols is not None else sample_columns(df)
    if not cols:
        raise ValueError("no per-sample columns to rank")

    # Rank genes WITHIN each sample (axis=0 = down the gene rows, per column).
    ranks = df[cols].rank(axis=0, pct=True)

    out = pd.DataFrame(
        {
            "Ensembl_Gene_ID": df["Ensembl_Gene_ID"].astype(str).to_numpy(),
            "Symbol": df["Symbol"].astype(str).to_numpy(),
        }
    )
    for _idcol in (
        "proteoform_key",
        "proteoform_members",
    ):  # carry proteoform identity (collapsed input)
        if _idcol in df.columns:
            out[_idcol] = df[_idcol].astype(str).to_numpy()
    for t in thresholds:
        pct = round((1.0 - t) * 100)
        out[f"frac_samples_top{pct}pct"] = (ranks >= t).mean(axis=1).to_numpy()
    out["n_samples"] = len(cols)
    return out


def cohort_percentile_vectors(
    df: pd.DataFrame,
    sample_cols: Iterable[str] | None = None,
    *,
    breakpoints: Iterable[int] = PERCENTILE_BREAKPOINTS,
    store_log1p: bool = True,
) -> pd.DataFrame:
    """Per-gene cohort percentile vector (the ``…-percentiles`` artifact).

    For each gene, take its expression across the cohort's samples and reduce that
    distribution to the ``breakpoints`` percentiles (``p0`` = min … ``p50`` =
    median … ``p100`` = max). Unlike :func:`within_sample_top_fractions` (the
    within-sample, across-genes axis), this is the within-cohort, across-samples
    axis — it lets a consumer place a sample's gene as a percentile rank within
    the cohort rather than an absolute TPM.

    Computed on whatever rows are passed in — the generator drops technical genes
    first, so the breakpoints describe the biological clean-TPM view. ``NaN``
    cells (a gene unmeasured in some samples) are ignored per gene. Stored as
    ``log1p`` (``store_log1p=True``) in ``float16`` for compactness, exactly the
    encoding :func:`oncoref.expression.cohort_gene_percentiles` restores with
    ``expm1``. Returns one row per gene with ``Ensembl_Gene_ID``, ``Symbol`` and a
    ``p{n}`` column per breakpoint.
    """
    cols = list(sample_cols) if sample_cols is not None else sample_columns(df)
    if not cols:
        raise ValueError("no per-sample columns to summarize")
    bps = list(breakpoints)

    mat = df[cols].to_numpy(dtype=float)
    if store_log1p:
        mat = np.log1p(mat)
    # nanpercentile down the sample axis (axis=1) -> shape (len(bps), n_genes).
    # all-NaN gene rows yield NaN (np warns); suppress since it's expected.
    with np.errstate(all="ignore"):
        q = np.nanpercentile(mat, bps, axis=1)

    out = pd.DataFrame(
        {
            "Ensembl_Gene_ID": df["Ensembl_Gene_ID"].astype(str).to_numpy(),
            "Symbol": df["Symbol"].astype(str).to_numpy(),
        }
    )
    for _idcol in (
        "proteoform_key",
        "proteoform_members",
    ):  # carry proteoform identity (collapsed input)
        if _idcol in df.columns:
            out[_idcol] = df[_idcol].astype(str).to_numpy()
    for i, bp in enumerate(bps):
        out[f"p{bp}"] = q[i].astype("float16")
    return out


def representative_sample_columns(
    selection_df: pd.DataFrame,
    sample_cols: Iterable[str] | None = None,
    *,
    k: int = 5,
    distance_log1p: bool = True,
) -> list[str]:
    """Choose representative sample columns from a selection matrix.

    ``selection_df`` defines only the geometry used for picking samples. For the
    shipped oncoref representative artifacts this is the biological clean-TPM
    matrix with ribosomal/technical rows removed, so technical composition cannot
    choose the medoids. Values can then be copied from a separate full clean-TPM
    matrix with the same sample columns.

    Ties are resolved by lexicographic sample id order, making the result stable
    even when an input parquet happens to carry columns in a different order.
    """
    cols = list(sample_cols) if sample_cols is not None else sample_columns(selection_df)
    missing = [c for c in cols if c not in selection_df.columns]
    if missing:
        raise ValueError(f"selection matrix is missing sample columns: {missing}")
    if not cols:
        raise ValueError("no per-sample columns to choose from")

    ordered = sorted(cols, key=str)
    if len(ordered) <= k:
        return ordered

    mat = selection_df[ordered].to_numpy(dtype=float).T  # samples x genes
    if distance_log1p:
        mat = np.log1p(mat)
    mat = np.nan_to_num(mat, nan=0.0)

    # Pairwise squared Euclidean via the ||a-b||^2 = ||a||^2 + ||b||^2 - 2a.b
    # identity (avoids materializing an n x n x g intermediate).
    gram = mat @ mat.T
    sq_norms = np.diag(gram)
    sq = sq_norms[:, None] + sq_norms[None, :] - 2.0 * gram
    dist = np.sqrt(np.maximum(sq, 0.0))

    selected = [int(np.argmin(dist.sum(axis=1)))]  # central medoid
    while len(selected) < k:
        min_to_selected = dist[:, selected].min(axis=1)
        min_to_selected[selected] = -np.inf  # never re-pick
        selected.append(int(np.argmax(min_to_selected)))

    return [ordered[i] for i in selected]


def cohort_medoids(
    df: pd.DataFrame,
    sample_cols: Iterable[str] | None = None,
    *,
    k: int = 5,
    distance_log1p: bool = True,
    selection_df: pd.DataFrame | None = None,
) -> pd.DataFrame:
    """Pick ``k`` representative real per-sample vectors spanning a cohort.

    The packaged cohort references are aggregates; this selects a bounded set of
    *real* per-sample columns to keep (the ``…-representatives`` artifact). The
    first pick is the cohort medoid — the sample minimizing total distance to all
    others (the most central, "typical" tumor). Each subsequent pick is the
    sample farthest (max–min Euclidean distance) from those already chosen, a
    deterministic farthest-first traversal that spreads the picks across the
    within-cohort variation rather than clustering them near the center.

    Distance is computed on ``log1p`` TPM (``distance_log1p=True``) so a few
    very-high-TPM genes don't dominate the geometry. If ``selection_df`` is
    provided, it supplies the geometry while returned values still come from
    ``df``; this is how the build pipeline selects on biological clean TPM but
    stores full clean_tpm_16_9_75 vectors. Cohorts with ``≤ k`` samples keep all
    of them in stable sample id order. Returns ``Ensembl_Gene_ID``, ``Symbol`` and
    the selected sample columns (original names), medoid first.
    """
    cols = list(sample_cols) if sample_cols is not None else sample_columns(df)
    missing = [c for c in cols if c not in df.columns]
    if missing:
        raise ValueError(f"value matrix is missing sample columns: {missing}")
    if not cols:
        raise ValueError("no per-sample columns to choose from")
    base = ["Ensembl_Gene_ID", "Symbol"]

    keep = representative_sample_columns(
        selection_df if selection_df is not None else df,
        sample_cols=cols,
        k=k,
        distance_log1p=distance_log1p,
    )
    return df[base + keep].reset_index(drop=True)
